In [17]:

from skimage.io import imread
from skimage.transform import resize
from skimage.feature import hog
from skimage import exposure
from tensorflow.keras.preprocessing.image import img_to_array
import matplotlib.pyplot as plt
from imutils import paths
import numpy as np
import cv2
import matplotlib.image as mpimg

datapath="C:/Users/20112/Desktop/keras-video-classification/keras-video-classification/data/qutub_minar"
imagePaths = list(paths.list_images(datapath))


In [18]:

csv_data=[]
for imagePath in imagePaths:
        print (imagePath)
        if imagePath.endswith(".jpg" or ".png"):
                img = mpimg.imread(imagePath)
                image_resized = resize(img, (128, 128))


        fd, hog_image = hog(image_resized, orientations=9, pixels_per_cell=(8, 8),
        cells_per_block=(2, 2), visualize=True, multichannel=True)
        
                                
        
        csv_data.append(fd)
        
datanp=np.array(csv_data)



# construct the image generator for data augmentation then
# initialize the total number of images generated thus far


for i in range(len(datanp)):

       
        print(csv_data[i])

  
       
        

C:/Users/20112/Desktop/keras-video-classification/keras-video-classification/data/qutub_minar\1.jpg
C:/Users/20112/Desktop/keras-video-classification/keras-video-classification/data/qutub_minar\10.jpg
C:/Users/20112/Desktop/keras-video-classification/keras-video-classification/data/qutub_minar\100.jpg
C:/Users/20112/Desktop/keras-video-classification/keras-video-classification/data/qutub_minar\101.jpg
C:/Users/20112/Desktop/keras-video-classification/keras-video-classification/data/qutub_minar\102.jpg
C:/Users/20112/Desktop/keras-video-classification/keras-video-classification/data/qutub_minar\103.jpg
C:/Users/20112/Desktop/keras-video-classification/keras-video-classification/data/qutub_minar\104.jpeg
C:/Users/20112/Desktop/keras-video-classification/keras-video-classification/data/qutub_minar\105.jpg
C:/Users/20112/Desktop/keras-video-classification/keras-video-classification/data/qutub_minar\106.jpg
C:/Users/20112/Desktop/keras-video-classification/keras-video-classification/data/qu

In [19]:
for i in range(len(datanp)):

        print(csv_data[i])



[0.         0.         0.         ... 0.18949943 0.01724435 0.05149424]
[0.27033192 0.27033192 0.14210145 ... 0.00193873 0.00072822 0.00104496]
[0.23065491 0.04949058 0.2238663  ... 0.0290097  0.03605004 0.17943636]
[0.19462821 0.05598543 0.01762734 ... 0.0570126  0.18017163 0.28952476]
[0.22751489 0.12272675 0.06236736 ... 0.13299172 0.26607728 0.26607728]
[0.03692902 0.         0.         ... 0.05657794 0.00895478 0.09927918]
[0.03692902 0.         0.         ... 0.05657794 0.00895478 0.09927918]
[0.28946452 0.07646898 0.07788621 ... 0.04327953 0.11710517 0.12732374]
[0.08219132 0.         0.08641494 ... 0.01384273 0.19646873 0.25972442]
[0.         0.         0.         ... 0.02837537 0.05898932 0.04084983]
[0.15436748 0.11132993 0.16817331 ... 0.03337685 0.00867365 0.        ]
[0.08480317 0.         0.10543336 ... 0.02406271 0.04841768 0.01979576]
[0.22966308 0.08237373 0.03208766 ... 0.12843492 0.04109046 0.04646662]
[0.15082085 0.06032938 0.         ... 0.03640188 0.0848838  0.11